### ISSUE TITLE
formioTranslate translate strings that are typed by the user

### ISSUE THREAD

**Issue by AbdallaElabd** [formio/ngFormio#303] opened 2017-02-14 15:27 UTC
Noticed formio is using the filter `formioTranslate` which is used to translate some hardcoded strings like error strings and what not.

But it's also being used to translate field labels which could be typed by the user himself
`<label>{{ component.label | formioTranslate:null:builder }}</label>`

That means that if the user adds a new field with the label "Name", it'd be translated to "Nom, Navn, ..." which might doesn't make sense because that's a string typed by the user himself.

Is there a way to fix this?

The way we tried getting around it was by using a decorator to override the formioTranslate filter, but that doesn't completely fix the problem.

**Comment by andreiho** [comment] 2017-02-27 08:29
@travist @randallknutson Any comment on this issue? We're curious why this was implemented this way. I can't understand why you'd pass input from the user through the translation service. We can easily work around it, but would be nice if you let us know if this is intended use or just something you overlooked.

**Comment by kperusko** [comment] 2017-06-08 16:07
Based on the [form.io documentation](https://help.form.io/developer/info/angular/#form-translation) this seems like the intended behavior.

**Comment by daneformio** [comment] 2024-02-14 14:16
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Closed by daneformio** 2024-02-14 14:16 UTC
